### ISSUE TITLE
Solo6010 driver not building on 3.0.0 kernel

### ISSUE THREAD

**Issue by tristam** [bluecherrydvr/solo6x10#14]
I was trying to install bluecherrydvr and the solo6010 driver on an ubuntu derivative based on Lucid LTS.  The distro in question has updated to the 3.0 kernel.  I get the following during sudo apt-get install solo6010-dkms:

Removing all [solo6010-2.3.6] DKMS Modules

Error! There are no instances of module: solo6010
2.3.6 located in the DKMS tree.
Done.
Adding [solo6010-2.3.6] Module to DKMS build system
Doing initial module build

Error! Bad return status for module build on kernel: 3.0.0-9-generic (i686)
Consult the make.log in the build directory
/var/lib/dkms/solo6010/2.3.6/build/ for more information.
dpkg: error processing solo6010-dkms (--configure):
 subprocess installed post-installation script returned error exit status 10
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Errors were encountered while processing:
 solo6010-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

The indicated make.log contains the following:

cat /var/lib/dkms/solo6010/2.3.6/build/make.log
DKMS make.log for solo6010-2.3.6 for kernel 3.0.0-9-generic (i686)
Tue Sep 20 10:56:15 EDT 2011
make: Entering directory `/usr/src/linux-headers-3.0.0-9-generic'
  LD      /var/lib/dkms/solo6010/2.3.6/build/built-in.o
  CC [M]  /var/lib/dkms/solo6010/2.3.6/build/solo6010-core.o
/var/lib/dkms/solo6010/2.3.6/build/solo6010-core.c: In function ‘solo6010_pci_probe’:
/var/lib/dkms/solo6010/2.3.6/build/solo6010-core.c:429: error: implicit declaration of function ‘mdelay’
make[1]: *** [/var/lib/dkms/solo6010/2.3.6/build/solo6010-core.o] Error 1
make: *** [_module_/var/lib/dkms/solo6010/2.3.6/build] Error 2
make: Leaving directory`/usr/src/linux-headers-3.0.0-9-generic'

Thanks!

--Jason
