### ISSUE TITLE
: error: implicit declaration of function ‘v4l2_ctrl_next’ - Ubuntu 16.04 .. help

### ISSUE THREAD

**Issue by aviadoffer** [bluecherrydvr/solo6x10#78]
aviad@ipdvr:~/bluecheery/solo6x10-master$ make
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
make  -C /lib/modules/4.4.0-22-generic/build M=/home/aviad/bluecheery/solo6x10-master modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-22-generic'
  CC [M]  /home/aviad/bluecheery/solo6x10-master/solo6x10-core.o
  CC [M]  /home/aviad/bluecheery/solo6x10-master/solo6x10-i2c.o
  CC [M]  /home/aviad/bluecheery/solo6x10-master/solo6x10-p2m.o
  CC [M]  /home/aviad/bluecheery/solo6x10-master/solo6x10-v4l2.o
/home/aviad/bluecheery/solo6x10-master/solo6x10-v4l2.c: In function ‘solo_disp_queryctrl’:
/home/aviad/bluecheery/solo6x10-master/solo6x10-v4l2.c:731:11: error: implicit declaration of function ‘v4l2_ctrl_next’ [-Werror=implicit-function-declaration]
  qc->id = v4l2_ctrl_next(solo_ctrl_classes, qc->id);
           ^
/home/aviad/bluecheery/solo6x10-master/solo6x10-v4l2.c: At top level:
/home/aviad/bluecheery/solo6x10-master/solo6x10-v4l2.c:802:2: error: unknown field ‘ioctl’ specified in initializer
  .ioctl   = video_ioctl2,
  ^
/home/aviad/bluecheery/solo6x10-master/solo6x10-v4l2.c:802:13: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .ioctl   = video_ioctl2,
             ^
/home/aviad/bluecheery/solo6x10-master/solo6x10-v4l2.c:802:13: note: (near initialization for ‘solo_v4l2_fops.open’)
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/home/aviad/bluecheery/solo6x10-master/solo6x10-v4l2.o' failed
make[2]: *** [/home/aviad/bluecheery/solo6x10-master/solo6x10-v4l2.o] Error 1
Makefile:1396: recipe for target '_module_/home/aviad/bluecheery/solo6x10-master' failed
make[1]: *** [_module_/home/aviad/bluecheery/solo6x10-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-22-generic'
Makefile:24: recipe for target 'modules' failed
make: *** [modules] Error 2
aviad@ipdvr:~/bluecheery/solo6x10-master$ uname -a
Linux ipdvr 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
aviad@ipdvr:~/bluecheery/solo6x10-master$

Help ?

**Comment by curtishall** [comment]
solo6x10 requires a 3.16 kernel

Thanks

**Comment by aviadoffer** [comment]
Thanks much for the quick answer. I moved to 4.4. Any chance anyone can fix it ?
Or , how to I get zoneminder to work with Bluecherry on Ubuntu 16.04 ?

**Comment by curtishall** [comment]
We've end of life'd the cards using the solo6x10 chipset.  There was some
porting for the solo6x10 driver in the staging branch of the kernel but if
I recall it was not very stable.

So...your best course would be to downgrade the kernel for now.

Thanks


On Wed, May 25, 2016 at 4:38 PM, aviadoffer <notifications@github.com>
wrote:

> Thanks much for the quick answer. I moved to 4.4. Any chance anyone can
> fix it ?
> Or , how to I get zoneminder to work with Bluecherry on Ubuntu 16.04 ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bluecherrydvr/solo6x10/issues/78#issuecomment-221715994>
>



-- 

Curtis Hall (curt@bluecherry.net <curt@corp.bluecherry.net>)
Bluecherry - www.bluecherrydvr.com / store.bluecherry.net
(877) 418-3391 x 283
(573) 642-6161 x 283

**Comment by aviadoffer** [comment]
Thanks much. I will get a new card that supports 4.4.
Much appreciate the quick help Sir!

**Comment by curtishall** [comment]
This card has 4.x support:

http://store.bluecherry.net/product/bluecherry-bc-h480p-16-16-port-video-16-port-audio-h-264-pcie-hardware-compression-capture-card-html/

Thanks

On Wed, May 25, 2016 at 4:42 PM, aviadoffer <notifications@github.com>
wrote:

> Thanks much. I will get a new card that supports 4.4.
> Much appreciate the quick help Sir!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bluecherrydvr/solo6x10/issues/78#issuecomment-221716935>
>



-- 

Curtis Hall (curt@bluecherry.net <curt@corp.bluecherry.net>)
Bluecherry - www.bluecherrydvr.com / store.bluecherry.net
(877) 418-3391 x 283
(573) 642-6161 x 283

**Comment by aviadoffer** [comment]
Thanks. Only need 8 ports and I only have one pci-e X1 free port.

**Comment by aviadoffer** [comment]
Using ffmpeg works fine with /dev/videoX
Configured zoneminder with ffmpeg and it works fine.

**Comment by andrey-utkin** [comment]
This way it utilizes the solo6x10 driver from upstream kernel you are running. This version of driver mostly works, but some bugs are known to show up in some setups. If it works well for you, then we're happy for you.

**Comment by aviadoffer** [comment]
Works great so far. Thank you.
