### ISSUE TITLE
Error during compilation on Linux kernel 3.19.0 (Ubuntu 14.04 64 bit)

### ISSUE THREAD

**Issue by bajobongo** [bluecherrydvr/solo6x10#77]
Hi,
I noticed that master isn't build on Ubuntu 14.04 LTS 64-bit (kernel: 3.19.0-56-generic). Console output:

```
name@host:~/Documents/solo6x10-master$ make
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
make  -C /lib/modules/3.19.0-56-generic/build M=/home/bajobongo/Documents/solo6x10-master modules
make[1]: Entering directory `/usr/src/linux-headers-3.19.0-56-generic'
  CC [M]  /home/bajobongo/Documents/solo6x10-master/solo6x10-v4l2.o
/home/bajobongo/Documents/solo6x10-master/solo6x10-v4l2.c: In function ‘solo_disp_queryctrl’:
/home/bajobongo/Documents/solo6x10-master/solo6x10-v4l2.c:731:2: error: implicit declaration of function ‘v4l2_ctrl_next’ [-Werror=implicit-function-declaration]
  qc->id = v4l2_ctrl_next(solo_ctrl_classes, qc->id);
  ^
cc1: some warnings being treated as errors
make[2]: *** [/home/bajobongo/Documents/solo6x10-master/solo6x10-v4l2.o] Error 1
make[1]: *** [_module_/home/bajobongo/Documents/solo6x10-master] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.19.0-56-generic'
make: *** [modules] Error 2
name@host:~/Documents/solo6x10-master$ uname -a
Linux host 3.19.0-56-generic #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Best regards,
Marcin
